name: RSVP to Alice and JPs wedding 2024 October
title: null
description: Alice and JP are getting married! The wedding will be in Brazil, in late October 2024.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: G-Z8QXPZY2LP
