name: RSVP to Alice and JPs wedding 2024 October
title: Alice and JPs wedding 2024 October
description: October 25-27 of 2024 in S&atilde;o Paulo, Brazil! Alice 💞 JP Wedding

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: G-Z8QXPZY2LP
